version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nodejs-gmail-tc-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ~/docker_volume_postgres_gmail_tc:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   build: .
  #   container_name: nodejs-gmail-tc-app
  #   restart: always
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_HOST=db
  #     - DB_PORT=${DB_PORT}
  #     - DB_NAME=${DB_NAME}
  #     - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
  #     - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
  #     - GMAIL_REDIRECT_URI=${GMAIL_REDIRECT_URI}
  #     - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
  #   ports:
  #     - "3000:3000" # You can change the host port if needed
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm start

volumes:
  postgres_data:
